### ISSUE TITLE
[Bug] "Can't find system Files app" toast on Android 13

### ISSUE THREAD

**Issue by Bespectacat** [2bllw8/anemo#40] opened 2022-12-10 23:03 UTC
### Steps to reproduce

1. Download Anemo from F-Droid (regular repo)
2. Try to open app
3. App displays toast: "Can't find system Files app"

### Expectations

App should open and display the File Picker app

### Reality

App cannot find the system files app, as indicated in the toast. Does not open. 

### App version

2.5.0

### Android version

13 on Google Pixel 7 Pro

**Comment by 2bllw8** [comment] 2022-12-15 10:30
Hi, thanks for reporting this issue. Is the app visible from this "Google File Manager" app you mentioned?
Moreover could you please tell me what apps you see in the list of "Installed apps" (with "Show system" enabled) in the system Settings when you filter for "file"?

**Comment by Bespectacat** [comment] 2022-12-15 16:09
https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.files&hl=en_US&gl=US

I should have included a link to the file manager in question earlier, my apologies. What I've referred to before has been linked above. Otherwise, yes, the Anemo app is visible from it, but it only displays the same toast as before when selected.

![photo_2022-12-15_11-01-24](https://user-images.githubusercontent.com/93142187/207908881-f452ee51-a55a-4818-acf9-6188f82e123a.jpg)


As for the apps in the search query, I see two apps appear: "Files" and "Files by Google." The second one being the aforementioned app linked above. The Files by Google app has an option to open it while the prior one does not.

![photo_2022-12-15_11-07-36](https://user-images.githubusercontent.com/93142187/207910101-77d4a79e-9650-42bc-86bb-51b4bd203887.jpg)

**Comment by Arragonder91** [comment] 2022-12-15 18:53
I am having the same issue on samsung S21 ultra since installing android 13.

 The update to 13 seems to have also borked F-droid as it'll say it's updating or downgrading an app but nothing will actually happen. You're not the dev so that's just context that might help

**Comment by 2bllw8** [comment] 2022-12-16 11:28
> As for the apps in the search query, I see two apps appear: "Files" and "Files by Google." 
> 
> ![photo_2022-12-15_11-07-36](https://user-images.githubusercontent.com/93142187/207910101-77d4a79e-9650-42bc-86bb-51b4bd203887.jpg)

It appears the app Anemo is looking for is installed (it's the first one with the blue and white icon), but I guess Google changed some internal name.

Are you by chance able to execute this adb command that generates a list of "activities" that are available for the Files app:

```
adb shell "dumpsys package | grep documents"
```

That'd help me add the new target so the app can work again, thanks

**Comment by Bespectacat** [comment] 2022-12-16 14:05
Sure thing, I'll get right on it

**Comment by Bespectacat** [comment] 2022-12-16 15:21
Here's what the adb command returned:

```ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        1666803 com.google.android.documentsui/com.android.documentsui.ScopedAccessActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        9548db9 com.google.android.documentsui/com.android.documentsui.selection.demo.SelectionDemoActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        5bc328b com.google.android.documentsui/com.android.documentsui.LauncherActivity
        bcd82bd com.google.android.documentsui/com.android.documentsui.ViewDownloadsActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        ca9071e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        66a6f81 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6f48d4e com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        5dd815f com.google.android.documentsui/com.android.documentsui.PackageReceiver
        782d47b com.google.android.documentsui/com.android.documentsui.PreBootReceiver
        7a74c75 com.google.android.documentsui/com.android.documentsui.roots.BootReceiver
        82d3af1 com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider
        bba3ab8 exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
  Permission [com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION] (6725582):
    sourcePackage=com.google.android.documentsui
    perm=PermissionInfo{9483493 com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION}
  com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider:
    Provider{f7830ca com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
  com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider:
    Provider{82d3af1 com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
  com.google.android.documentsui/androidx.startup.InitializationProvider:
    Provider{ef502f2 com.google.android.documentsui/androidx.startup.InitializationProvider}
  com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider:
    Provider{8a88967 com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
  exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider:
    Provider{bba3ab8 exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider}
  [com.android.documentsui.archives]:
    Provider{82d3af1 com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
      applicationInfo=ApplicationInfo{a2d8818 com.google.android.documentsui}
  [com.android.documentsui.pickCountRecord]:
    Provider{f7830ca com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
      applicationInfo=ApplicationInfo{3a977db com.google.android.documentsui}
  [com.android.shell.documents]:
  [com.android.mtp.documents]:
  [com.android.traceur.documents]:
  [exe.bbllw8.anemo.documents]:
    Provider{bba3ab8 exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider}
  [com.android.documentsui.lastAccessed]:
    Provider{8a88967 com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
      applicationInfo=ApplicationInfo{cb98a43 com.google.android.documentsui}
  [com.android.providers.downloads.documents]:
  [com.android.externalstorage.documents]:
  [com.termux.documents]:
  [com.google.android.documentsui.androidx-startup]:
    Provider{ef502f2 com.google.android.documentsui/androidx.startup.InitializationProvider}
      applicationInfo=ApplicationInfo{f84abc0 com.google.android.documentsui}
  [com.android.providers.media.documents]:
  [com.example.documents]:
  [com.google.android.documentsui.theme.pixel]
  [com.google.android.documentsui]
    queriesPackages=[com.android.documentsui, com.google.android.documentsui]
  Package [com.google.android.documentsui.theme.pixel] (8109a79):
    pkg=Package{b8d3be com.google.android.documentsui.theme.pixel}
    dataDir=/data/user/0/com.google.android.documentsui.theme.pixel
    overlayTarget=com.google.android.documentsui
  Package [com.google.android.documentsui] (7ffe275):
    pkg=Package{a71420a com.google.android.documentsui}
    codePath=/data/app/~~rrEKntugsdEpqY0Uoqq0PQ==/com.google.android.documentsui-XFXPyaasOlRJYjYkAsqPVQ==
    resourcePath=/data/app/~~rrEKntugsdEpqY0Uoqq0PQ==/com.google.android.documentsui-XFXPyaasOlRJYjYkAsqPVQ==
    legacyNativeLibraryDir=/data/app/~~rrEKntugsdEpqY0Uoqq0PQ==/com.google.android.documentsui-XFXPyaasOlRJYjYkAsqPVQ==/lib
    dataDir=/data/user/0/com.google.android.documentsui
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: prot=signature, INSTALLED
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted=true
        com.android.documentsui.LauncherActivity
        com.android.documentsui.ViewDownloadsActivity
  Package [com.google.android.documentsui] (6db0bd4):
    pkg=Package{2d6d17d com.google.android.documentsui}
    dataDir=/data/user/0/com.google.android.documentsui
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: prot=signature
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted=true
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
      com.google.android.documentsui:
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
  [com.google.android.documentsui.theme.pixel]
  [com.google.android.documentsui]
    path: /data/app/~~rrEKntugsdEpqY0Uoqq0PQ==/com.google.android.documentsui-XFXPyaasOlRJYjYkAsqPVQ==/base.apk
  [com.google.android.documentsui.theme.pixel]
  [com.google.android.documentsui]
      appPackageName=com.google.android.documentsui appIcon=false appLabel=Google Play system update```

**Comment by Arragonder91** [comment] 2022-12-17 22:10
IDK if you wanted a dump from me as well but here's mine



PS D:\Downloads\Tools\platform-tools> .\adb shell "dumpsys package | grep documents"
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        d1dd88d com.google.android.documentsui/com.android.documentsui.ScopedAccessActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        c98ba53 com.google.android.documentsui/com.android.documentsui.selection.demo.SelectionDemoActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        1c803d5 com.google.android.documentsui/com.android.documentsui.LauncherActivity
        10439b7 com.google.android.documentsui/com.android.documentsui.ViewDownloadsActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        aebde7e exe.bbllw8.anemo/.documents.receiver.ReceiverActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        7fdcadb com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        85b0e60 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        d1c7089 com.google.android.documentsui/com.android.documentsui.PackageReceiver
        2528c45 com.google.android.documentsui/com.android.documentsui.PreBootReceiver
        8eaa8af com.google.android.documentsui/com.android.documentsui.roots.BootReceiver
        86f5718 exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider
        dc320cb com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider
  Permission [com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION] (dacd276):
    sourcePackage=com.google.android.documentsui
    perm=PermissionInfo{7f9c077 com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION}
  com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider:
    Provider{a842031 com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
  com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider:
    Provider{dc320cb com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
  com.google.android.documentsui/androidx.startup.InitializationProvider:
    Provider{354bffe com.google.android.documentsui/androidx.startup.InitializationProvider}
  com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider:
    Provider{d27578c com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
  exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider:
    Provider{86f5718 exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider}
  [com.android.documentsui.archives]:
    Provider{dc320cb com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
      applicationInfo=ApplicationInfo{736fc1e com.google.android.documentsui}
  [com.android.documentsui.pickCountRecord]:
    Provider{a842031 com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
      applicationInfo=ApplicationInfo{1ad38e com.google.android.documentsui}
  [com.android.shell.documents]:
  [com.android.mtp.documents]:
  [com.android.traceur.documents]:
  [exe.bbllw8.anemo.documents]:
    Provider{86f5718 exe.bbllw8.anemo/.documents.provider.AnemoDocumentProvider}
  [com.dropbox.product.android.dbapp.document_provider.documents]:
  [com.android.documentsui.lastAccessed]:
    Provider{d27578c com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
      applicationInfo=ApplicationInfo{1e81273 com.google.android.documentsui}
  [com.android.providers.downloads.documents]:
  [com.android.externalstorage.documents]:
  [com.google.android.documentsui.androidx-startup]:
    Provider{354bffe com.google.android.documentsui/androidx.startup.InitializationProvider}
      applicationInfo=ApplicationInfo{4dac027 com.google.android.documentsui}
  [com.android.providers.media.documents]:
  [com.example.documents]:
  [com.google.android.overlay.modules.documentsui]
  [com.google.android.documentsui]
    queriesPackages=[com.android.documentsui, com.google.android.documentsui]
  Package [com.google.android.overlay.modules.documentsui] (298c519):
    pkg=Package{6d0024c com.google.android.overlay.modules.documentsui}
    dataDir=/data/user/0/com.google.android.overlay.modules.documentsui
    overlayTarget=com.google.android.documentsui
  Package [com.google.android.documentsui] (9126ee6):
    pkg=Package{645d6d3 com.google.android.documentsui}
    codePath=/data/app/~~jyLne1YhNzWgyydjKHS_jQ==/com.google.android.documentsui-cW6ljadx9uRBcPlL3JSHIg==
    resourcePath=/data/app/~~jyLne1YhNzWgyydjKHS_jQ==/com.google.android.documentsui-cW6ljadx9uRBcPlL3JSHIg==
    legacyNativeLibraryDir=/data/app/~~jyLne1YhNzWgyydjKHS_jQ==/com.google.android.documentsui-cW6ljadx9uRBcPlL3JSHIg==/lib
    dataDir=/data/user/0/com.google.android.documentsui
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: prot=signature, INSTALLED
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted=true
        com.android.documentsui.LauncherActivity
  Package [com.google.android.documentsui] (cad4ee5):
    pkg=Package{df28dba com.google.android.documentsui}
    dataDir=/data/user/0/com.google.android.documentsui
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: prot=signature
      com.google.android.documentsui.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION: granted=true
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
      com.google.android.documentsui:
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
  [com.google.android.overlay.modules.documentsui]
  [com.google.android.documentsui]
    path: /data/app/~~jyLne1YhNzWgyydjKHS_jQ==/com.google.android.documentsui-cW6ljadx9uRBcPlL3JSHIg==/base.apk
  [com.google.android.overlay.modules.documentsui]
  [com.google.android.documentsui]
  [com.google.android.documentsui]
    path: /data/app/~~jyLne1YhNzWgyydjKHS_jQ==/com.google.android.documentsui-cW6ljadx9uRBcPlL3JSHIg==/base.apk
    path: /data/app/~~jyLne1YhNzWgyydjKHS_jQ==/com.google.android.documentsui-cW6ljadx9uRBcPlL3JSHIg==/split_config.xxhdpi.apk

**Comment by Bespectacat** [comment] 2023-01-04 14:27
Hey that's perfectly fine. Sucks that they would do that though, especially considering how their Google Files app has some trackers and other nonsense in it (trackers in a file browser??). Thanks for the update!

**Comment by arielsbecker** [comment] 2023-01-08 15:41
Hi! I'm affected by this issue too. Can anyone point me to where I can complain about this? I feel like Google betrayed me for the umpteenth time with more and more unwanted and uncalled for restrictions.

**Comment by locuturus** [comment] 2023-01-15 03:40
Hello, I think there may still be a way to do this. "Files" by "Marc apps & software" in the Google Play Store also invokes DocumentsUI and it operates as normal on my Android 13 Xperia phone while your app throws that toast error.

**Comment by 2bllw8** [comment] 2023-01-15 10:38
> Hello, I think there may still be a way to do this. "Files" by "Marc apps & software" in the Google Play Store also invokes DocumentsUI and it operates as normal on my Android 13 Xperia phone while your app throws that toast error.

Thanks for this suggestion. I've given a look at that app and tried to implement a fix for this issue based on the code of that app.
It makes use of some undocumented APIs, this means it might break in future Android versions, but for now it should be ok.

Could you please test the 
[apk in this zip](https://github.com/2bllw8/anemo/files/10419949/app-release.apk.zip) and let me know if it works now?
If so, I can upload the fix and release a new version for everyone

**Comment by arielsbecker** [comment] 2023-01-15 14:27
Hi @2bllw8. Just tested this apk on my Android 5.10.66, it is still showing the toast. However, earlier this week when I had the same issue, I factory-resetted my phone and the version that's available on F-Droid worked perfectly for some days until it stopped working; I didn't do any system update, so I think maybe it's related to some instant app installing itself.

I have a Samsung A33, UI v5, Android 13, last system update November 1st, 2022, last security patch October 1st, 2022 (almost sure everything's at factory settings).

**Comment by Bespectacat** [comment] 2023-01-16 18:48
I've attempted to use the apk in the zip provided to no avail, the same toast still appears. Made sure to uninstall and remove any traces of the original instance I already had installed before installing this one too, just to be sure.

**Comment by locuturus** [comment] 2023-01-16 18:51
> Thanks for this suggestion. I've given a look at that app and tried to implement a fix for this issue based on the code of that app. It makes use of some undocumented APIs, this means it might break in future Android versions, but for now it should be ok.
> 
> Could you please test the [apk in this zip](https://github.com/2bllw8/anemo/files/10419949/app-release.apk.zip) and let me know if it works now? If so, I can upload the fix and release a new version for everyone

I wondered if Marc was doing something undocumented. Older versions of that app would invoke an open-with dialogue populated by Files (AOSP) and Files (by Google, Samsung, whatever) until you set the default. Sometimes you had to disable the OEM Files app to clear the preset defaults and be allowed to choose Files (AOSP). I assumed it was somehow calling Settings > Storage > Files. But now in A13 'Files' is not an option anymore. Weird choice, even for Mr "what is structured local storage and why do you _think_ you want it" Google in my opinion.

Anyway A) your test app did not work for me on a Pixel, and B) it's still possible to make a shortcut to DocumentsUI activity "Downloads" so that could be a backup plan.

**Comment by locuturus** [comment] 2023-01-23 02:31
By the way, Shelter uses the intent below. It works, but will open the root of the Downloads provider rather than the root of primary storage.

> intent:#Intent;type=vnd.android.document/root;launchFlags=0x3000000;end 
------------ 
> ACTION: android.intent.action.VIEW 
MIME: vnd.android.document/root 
URI: intent:#Intent;type=vnd.android.document/root;launchFlags=0x3000000;end 
FLAGS: 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 

------------ 
> MATCHING ACTIVITIES: 
Files (com.google.android.documentsui - com.android.documentsui.files.FilesActivity) 
Interceptor (io.github.muntashirakon.AppManager - io.github.muntashirakon.AppManager.intercept.ActivityInterceptor)

**Comment by 2bllw8** [comment] 2023-01-25 10:46
Thanks everyone who reported back their findings, I've made a new test version. Let me know if this one is working for you
[app-release.apk.zip](https://github.com/2bllw8/anemo/files/10498497/app-release.apk.zip)
Unfortunately this issue can't be reproduced on the official emulator images, nor I have a device with Android 13 to verify whether or not it works on my own. Thank you for helping with this again

**Comment by arielsbecker** [comment] 2023-01-25 11:52
It works for me! Samsung A33, UI v5, Android 13 with kernel 5.10.66, last system update November 1st, 2022, last security patch October 1st, 2022.

**Comment by Bespectacat** [comment] 2023-01-25 12:35
Just downloaded and tested it out for myself as well. Works just fine! 

This is from a Pixel 7 Pro with Android 13 (Kernel 5.10.107, last update Nov 1, 2022, security update Jan 5, 2023)

**Comment by Ilithy** [comment] 2023-01-25 14:19
Work for me too.
On Pixel 6 pro under Grapheneos (latest stable) - A13

Thanks for the work ❤️🙏

**Comment by 2bllw8** [comment] 2023-01-28 18:43
Thanks everyone for the help, enjoy the newest [2.6.0](https://github.com/2bllw8/anemo/releases/tag/v2.6.0) release that includes the bug fix for this and a new feature as well

**Closed by 2bllw8** 2023-01-28 18:43 UTC
Labels: bug

**Comment by locuturus** [comment] 2023-01-29 05:39
Thanks for your efforts! By the way, I discovered an intent format that actually opens DocumentsUI with a specific (shared storage) folder path! I'll paste it here because I'm excited but I suspect your app doesn't really need to do that. Syncthing on the other hand...

The below can invoke DocumentsUI and have it open DCIM/Camera:
> URI	intent://com.android.externalstorage.documents/document/primary%3ADCIM%2FCamera#Intent;scheme=content;type=vnd.android.document/directory;launchFlags=0x23000000;end
>
> VERSION	1
ACTION	android.intent.action.VIEW
DATA	content://com.android.externalstorage.documents/document/primary%3ADCIM%2FCamera
TYPE	vnd.android.document/directory
FLAGS	0x23000000
>
>MATCHING ACTIVITIES	4
0	LABEL  	Files
 	NAME   	com.android.documentsui.files.FilesActivity
 	PACKAGE	com.google.android.documentsui
1	LABEL  	Intent Intercept
 	NAME   	uk.co.ashtonbrsc.intentexplode.Explode
 	PACKAGE	de.k3b.android.intentintercept
2	LABEL  	Interceptor
 	NAME   	io.github.muntashirakon.AppManager.intercept.ActivityInterceptor
 	PACKAGE	io.github.muntashirakon.AppManager
3	LABEL  	Material Files
 	NAME   	me.zhanghai.android.files.filelist.FileListActivity
 	PACKAGE	me.zhanghai.android.files
