### ISSUE TITLE
"Can't find System Files app"

### ISSUE THREAD

**Issue by TriStaRvOiD** [2bllw8/anemo#8] opened 2022-03-19 11:20 UTC
I'm getting a toast saying that the app isn't able to detect the android file manager.
But I'm pretty sure this is a bug because I checked with a package manager, and com.google.android.documentsui (The system file app) is actually there on my phone.

• Samsung phone, OneUI 4.0
• Android 12
• Anemo version 2.1 from Izzyondroid

**Comment by 2bllw8** [comment] 2022-03-19 19:05
Hi, could you please run the following adb command and upload the output here? It seems like Samsung devices need special handling since it's the second time I've seen this reported for Samsung devices.

The adb command I need the output of is:

`adb shell dumpsys package | grep "documentsui"`

**Comment by mwhdc** [comment] 2022-03-19 20:23
I'm getting the same toast on Pixel 6 Pro, Android 12L beta 3, with the IzzyOnDroid build.

```
    com.google.android.documentsui
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        d0d904d com.google.android.documentsui/com.android.documentsui.ScopedAccessActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        1bf8395 com.google.android.documentsui/com.android.documentsui.LauncherActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        1f49813 com.google.android.documentsui/com.android.documentsui.selection.demo.SelectionDemoActivity
        e29bb77 com.google.android.documentsui/com.android.documentsui.ViewDownloadsActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        edab09b com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        644c920 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        6afe449 com.google.android.documentsui/com.android.documentsui.PackageReceiver
        2097c05 com.google.android.documentsui/com.android.documentsui.PreBootReceiver
        986a26f com.google.android.documentsui/com.android.documentsui.roots.BootReceiver
        384f68b com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
            com.google.android.documentsui/com.android.documentsui.files.FilesActivity
  com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider:
    Provider{b0a654f com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
  com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider:
    Provider{384f68b com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
  com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider:
    Provider{1f3830c com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
  [com.android.documentsui.archives]:
    Provider{384f68b com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
      applicationInfo=ApplicationInfo{2834cf6 com.google.android.documentsui}
  [com.android.documentsui.pickCountRecord]:
    Provider{b0a654f com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
      applicationInfo=ApplicationInfo{d587631 com.google.android.documentsui}
  [com.android.documentsui.lastAccessed]:
    Provider{1f3830c com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
      applicationInfo=ApplicationInfo{4d3cfb4 com.google.android.documentsui}
  [com.google.android.documentsui.theme.pixel]
  [com.google.android.documentsui]
  Package [com.google.android.documentsui.theme.pixel] (a216d39):
    pkg=Package{2990f7e com.google.android.documentsui.theme.pixel}
    applicationInfo=PackageImpl{2990f7e com.google.android.documentsui.theme.pixel}
    dataDir=/data/user/0/com.google.android.documentsui.theme.pixel
    overlayTarget=com.google.android.documentsui
  Package [com.google.android.documentsui] (b63ad30):
    pkg=Package{b558da9 com.google.android.documentsui}
    codePath=/data/app/~~4kuYdyfvUkgX0xEMl-MMNA==/com.google.android.documentsui-iR0dM0DvsRyimOXfY6Tn5w==
    resourcePath=/data/app/~~4kuYdyfvUkgX0xEMl-MMNA==/com.google.android.documentsui-iR0dM0DvsRyimOXfY6Tn5w==
    legacyNativeLibraryDir=/data/app/~~4kuYdyfvUkgX0xEMl-MMNA==/com.google.android.documentsui-iR0dM0DvsRyimOXfY6Tn5w==/lib
    applicationInfo=PackageImpl{b558da9 com.google.android.documentsui}
    dataDir=/data/user/0/com.google.android.documentsui
        com.android.documentsui.LauncherActivity
        com.android.documentsui.ViewDownloadsActivity
  Package [com.google.android.documentsui] (a2bf1c5):
    pkg=Package{bbe271a com.google.android.documentsui}
    applicationInfo=PackageImpl{bbe271a com.google.android.documentsui}
    dataDir=/data/user/0/com.google.android.documentsui
    com.google.android.documentsui:
      com.google.android.documentsui [repeats about 60x]
  [com.google.android.documentsui.theme.pixel]
  [com.google.android.documentsui]
    path: /data/app/~~4kuYdyfvUkgX0xEMl-MMNA==/com.google.android.documentsui-iR0dM0DvsRyimOXfY6Tn5w==/base.apk
  [com.google.android.documentsui.theme.pixel]
  [com.google.android.documentsui]
```

**Comment by TriStaRvOiD** [comment] 2022-03-20 08:07
> Hi, could you please run the following adb command and upload the output here? It seems like Samsung devices need special handling since it's the second time I've seen this reported for Samsung devices.
> 
> The adb command I need the output of is:
> 
> `adb shell "dumpsys package | grep documentsui"`

Here's the output

```
com.google.android.documentsui
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        4dfd407 com.google.android.documentsui/com.android.documentsui.ScopedAccessActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        3a4435d com.google.android.documentsui/com.android.documentsui.selection.demo.SelectionDemoActivity
        1fdb20f com.google.android.documentsui/com.android.documentsui.LauncherActivity
        b486621 com.google.android.documentsui/com.android.documentsui.ViewDownloadsActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        d8524a5 com.google.android.documentsui/com.android.documentsui.files.FilesActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        22abf22 com.google.android.documentsui/com.android.documentsui.picker.PickActivity
        d9ba9a3 com.google.android.documentsui/com.android.documentsui.PackageReceiver
        ab53cff com.google.android.documentsui/com.android.documentsui.PreBootReceiver
        be6b859 com.google.android.documentsui/com.android.documentsui.roots.BootReceiver
        6418115 com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider
  com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider:
    Provider{ab4c3ee com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
  com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider:
    Provider{6418115 com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
  com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider:
    Provider{bd50e53 com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
  [com.android.documentsui.archives]:
    Provider{6418115 com.google.android.documentsui/com.android.documentsui.archives.ArchivesProvider}
      applicationInfo=ApplicationInfo{223c7b4 com.google.android.documentsui}
  [com.android.documentsui.pickCountRecord]:
    Provider{ab4c3ee com.google.android.documentsui/com.android.documentsui.picker.PickCountRecordProvider}
      applicationInfo=ApplicationInfo{2469910 com.google.android.documentsui}
  [com.android.documentsui.lastAccessed]:
    Provider{bd50e53 com.google.android.documentsui/com.android.documentsui.picker.LastAccessedProvider}
      applicationInfo=ApplicationInfo{4bf2022 com.google.android.documentsui}
  [com.google.android.overlay.modules.documentsui]
  [com.google.android.documentsui]
  Package [com.google.android.overlay.modules.documentsui] (10692):
    pkg=Package{ca3b802 com.google.android.overlay.modules.documentsui}
    applicationInfo=PackageImpl{ca3b802 com.google.android.overlay.modules.documentsui}
    dataDir=/data/user/0/com.google.android.overlay.modules.documentsui
    overlayTarget=com.google.android.documentsui
  Package [com.google.android.documentsui] (196fd3):
    pkg=Package{4539fe6 com.google.android.documentsui}
    codePath=/data/app/~~cxdZSpCJTQC2yIbU6IRpxA==/com.google.android.documentsui-MrKpHI6oqS1F7dzN0RVqwQ==
    resourcePath=/data/app/~~cxdZSpCJTQC2yIbU6IRpxA==/com.google.android.documentsui-MrKpHI6oqS1F7dzN0RVqwQ==
    legacyNativeLibraryDir=/data/app/~~cxdZSpCJTQC2yIbU6IRpxA==/com.google.android.documentsui-MrKpHI6oqS1F7dzN0RVqwQ==/lib
    applicationInfo=PackageImpl{4539fe6 com.google.android.documentsui}
    dataDir=/data/user/0/com.google.android.documentsui
        com.android.documentsui.LauncherActivity
  Package [com.google.android.documentsui] (96f34d4):
    pkg=Package{66a467d com.google.android.documentsui}
    applicationInfo=PackageImpl{66a467d com.google.android.documentsui}
    dataDir=/data/user/0/com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
      com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
      com.google.android.documentsui:
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
        com.google.android.documentsui
  [com.google.android.overlay.modules.documentsui]
  [com.google.android.documentsui]
    path: /data/app/~~cxdZSpCJTQC2yIbU6IRpxA==/com.google.android.documentsui-MrKpHI6oqS1F7dzN0RVqwQ==/base.apk
  [com.google.android.overlay.modules.documentsui]
  [com.google.android.documentsui]
2022-01-31 22:37:12.941: setApplicationHiddenSettingAsUser, packageName: com.google.android.documentsui, userId: 10, hidden: false, callingUid: 1000, callingPackage: system
2022-01-31 22:37:13.957: setApplicationHiddenSettingAsUser, packageName: com.android.documentsui, userId: 10, hidden: false, callingUid: 1000, callingPackage: system
2022-02-26 10:40:46.784: setApplicationHiddenSettingAsUser, packageName: com.google.android.documentsui, userId: 10, hidden: false, callingUid: 1000, callingPackage: system
2022-02-26 10:40:47.303: setApplicationHiddenSettingAsUser, packageName: com.android.documentsui, userId: 10, hidden: false, callingUid: 1000, callingPackage: system
04/12/2021 23:44: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
11/12/2021 11:29: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
15/12/2021 19:40: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
16/12/2021 16:30: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
18/12/2021 17:03: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
19/12/2021 18:11: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
21/12/2021 21:57: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
25/12/2021 11:45: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
29/12/2021 15:35: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
29/12/2021 16:00: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
29/12/2021 16:05: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
29/12/2021 16:23: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
29/12/2021 16:31: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
29/12/2021 22:37: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
31/12/2021 12:58: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
31/12/2021 13:23: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
31/12/2021 13:59: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
01/01/2022 15:58: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
01/01/2022 17:27: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
06/01/2022 09:53: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
06/01/2022 17:28: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
09/01/2022 13:30: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
10/01/2022 13:07: Relax SCAN_REQUIRE_KNOWN requirement for package com.google.android.documentsui
```

**Comment by TriStaRvOiD** [comment] 2022-03-20 08:13
For some reason the error is suddenly gone now. The documents UI is opening. I'm not sure why.

**Comment by TriStaRvOiD** [comment] 2022-03-20 08:48
However now I'm facing a different problem. The lock-unlock quick setting tile isn't working..

https://user-images.githubusercontent.com/58824912/159154850-882b984d-61de-47dc-8cd9-e1a9ce4e8b82.mp4

The password creation window isn't coming. 
Sorry that this isn't related to the original issue, maybe I'll create a separate one.

**Comment by 2bllw8** [comment] 2022-03-20 12:11
> Tested with a re-install (uninstall-install).
> 
> The "Can't find system file app" toast got displayed. But then I cleared app data, and it works.

This seems weird, I can't think of a reason why this would happen... The Files system app Anemo expects is available on both devices that sent the logs. Are you on Android 12 as well?

> The password creation window isn't coming.

If you don't have a password set no dialog will be shown. You can set a password on the configuration UI

**Comment by TriStaRvOiD** [comment] 2022-03-20 14:30
> > Tested with a re-install (uninstall-install).
> > 
> > The "Can't find system file app" toast got displayed. But then I cleared app data, and it works.
> 
> This seems weird, I can't think of a reason why this would happen... The Files system app Anemo expects is available on both devices that sent the logs. Are you on Android 12 as well?
> 

Yeah, I'm on Android 12

> > The password creation window isn't coming.
> 
> If you don't have a password set no dialog will be shown. You can set a password on the configuration UI

Um, where do I find this configuration UI?
Actually in version 2.0 of Anemo the Set Password window was coming up when you click on the qs tile.

**Comment by 2bllw8** [comment] 2022-03-20 15:37
> Yeah, I'm on Android 12

Ok, then I'll have to investigate on a non-emulator Android 12 device, thanks for the information
 
> Um, where do I find this configuration UI? Actually in version 2.0 of Anemo the Set Password window was coming up when you click on the qs tile (for the first time).

Either from the popup shortcut on the app icon long press or in Settings -> Apps -> Anemo -> More settings in the app

**Comment by mwhdc** [comment] 2022-03-20 16:48
> For some reason the error is suddenly gone now. The documents UI is opening. I'm not sure why.

Overnight the documentsui issue went away for me too. I didn't reboot and had already tried killing and reopening the Files app. There are some other UX quirks, but I'll file separate issues for those if I can reproduce. Interesting app @2bllw8, thanks for publishing it.

**Comment by TriStaRvOiD** [comment] 2022-03-20 17:02
> > Yeah, I'm on Android 12
> 
> Ok, then I'll have to investigate on a non-emulator Android 12 device, thanks for the information
>  

Yeah, no problem. I'm personally fed up with the current app I'm using for encrypting storage so I really needed an alternative. Thanks for creating this app.

> > Um, where do I find this configuration UI? Actually in version 2.0 of Anemo the Set Password window was coming up when you click on the qs tile (for the first time).
> 
> Either from the popup shortcut on the app icon long press or in Settings -> Apps -> Anemo -> More settings in the app. It's a new UI for the 2.1 version and it allows more options such as locking without a password
> 
> 

Working fine now, 👍.

**Comment by 2bllw8** [comment] 2022-03-21 09:02
> Edit 2: The more settings is actually coming as inapp notification settings😅

Samsung probably changed that string from stock android...

> Overnight the documentsui issue went away for me too

I'm both happy and puzzled about the issue mysteriously disappearing for both of you...
In any case, I have improved the code for finding the System Files app, when the next version comes it should be more better.

Let me know if you run into this issue again. If you have different things to report, please make a new issue here on GitHub

**Comment by 2bllw8** [comment] 2022-03-22 10:37
I have finally found the issue by testing on an Android 11 device, I will release a new version with a fix during this week.
Re-opening the issue until the next version is released

**Comment by 2bllw8** [comment] 2022-03-23 12:36
Version [2.1.1](https://github.com/2bllw8/anemo/releases/tag/v2.1.1) includes a fix for this issue.

**Closed by 2bllw8** 2022-03-23 12:36 UTC
Labels: bug

**Comment by TriStaRvOiD** [comment] 2022-03-24 01:32
> Version [2.1.1](https://github.com/2bllw8/anemo/releases/tag/v2.1.1) includes a fix for this issue.

Tested 2.1.1, working now👍
The toast still comes though

https://user-images.githubusercontent.com/58824912/159824196-d1135eae-7df6-4397-9f2d-77797a220875.mp4

**Comment by XPaimoNX** [comment] 2022-06-13 22:43
https://user-images.githubusercontent.com/101975343/173459527-bba60857-ef16-42d9-b4a4-c5e78c180282.mp4

Help using Xiaomi Poco F3 Custom Rom Miui Sr 22.5.22

**Comment by 2bllw8** [comment] 2022-06-14 07:14
> Miui Sr 22.5.22

I can't find any information about this "miui sr" on the internet, but the error

> `ContentService: Neither user 10054 nor current process has android.permission.CACHE_CONTENT`

makes it look like the rom you're running is using a modified system files application, since that permission is supposed to be [declared in `com.android.documentsui`](https://android.googlesource.com/platform/packages/apps/DocumentsUI/+/refs/heads/master/AndroidManifest.xml#28)

Please test again on stock miui, and if that still happens make a new issue

**Comment by XPaimoNX** [comment] 2022-06-14 10:59
I find the problem it just the module for mixplorer that installed as
system and the add ons on it cause the system to have error i guess but i
still got the cannot find the system

**Comment by WebUral** [comment] 2024-05-28 09:41
> Personally I don't think that has anything to do with mixplorer. You're using a custom rom, and if its based on miui then it's more of a mod. Either ask the devs behind the rom to fix it, or switch to stock.

This is definitely related to MiXplorer ... If MiX is installed as Magisk module or has been converted to priv-app — this causes DocumentsUI crashes ... Try revert MiXplorer (un-systemize) — and the android-File-App will work again

**Comment by realhuseyn** [comment] 2024-08-25 13:43
I had the same issue. Finally, I found the problem related to Microsoft Intune Company Portal. It works after uninstalling Company Portal. It creates the second files app, somehow caused by a crash
